version: "2"

services:
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.8-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8032:8032"
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8020:8020"
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    container_name: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
  hive-server:
    build: .
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
    ports:
      - "10000:10000"
  hive-metastore:
    build: .
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
  hue:
    image: gethue/hue:latest
    ports:
      - "8888:8888"
    links:
       - hive-server
    volumes:
        - ./conf/hue.ini:/hue/desktop/conf/pseudo-distributed.ini
  spark:
    build:
      context: ./livy
      dockerfile: Dockerfile
    container_name: livy
    ports:
      - "8998:8998"
